### ISSUE TITLE
Use Pipreqs for your requirements file

### ISSUE THREAD

**Issue by angeloschneiter** [andre-fuchs/kerning-pairs#34]
I think you used pipfreez for your request file, which makes it difficult to install the packages because of some version conflicts. If you use pipreqs for your request file, the file will be much smaller and you won't have any version conflicts.

New requirements:

beautifulsoup4==4.10.0
defcon==0.10.0
fonttools==4.43.0
fuzzywuzzy==0.18.0
pandas==1.3.5
python-slugify==8.0.4
Requests==2.32.2
svgwrite==1.4.1
tqdm==4.62.3
wikipedia==1.4.0

Info:
https://towardsdatascience.com/goodbye-pip-freeze-welcome-pipreqs-258d2e7a5a62

![image](https://github.com/andre-fuchs/kerning-pairs/assets/119105500/98be79ab-8adb-4793-b759-bea3b11da435)

**Comment by andre-fuchs** [comment]
Thanks @angeloschneiter for the reminder. I use the "pip-chill" package for that nowadays as well.
